name: GitHub CI

on: [pull_request, push]

jobs:
  gcc_simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt install check
        export CK_LOG_FILE_NAME=test-details.log
        ./configure
        make
        make check
        cat test/test-details.log

  clang_simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt install check
        export CK_LOG_FILE_NAME=test-details.log
        CC=clang ./configure
        make
        make check
        cat test/test-details.log

  # -Werror is not working with automake
  gcc_strict:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt install check
        export CK_LOG_FILE_NAME=test-details.log
        echo 'AM_CFLAGS = -Werror' >> src/Makefile.am
        CFLAGS='-DDEBUG_UNUSED -DPEDANTIC -pedantic -Wno-long-long -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wswitch -Wsign-compare -Wshadow -Wformat -Wtype-limits -Wundef -Wmissing-prototypes -Wstrict-prototypes -Wconversion' ./configure
        make
        make check
        cat test/test-details.log

  clang_strict:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt install check
        export CK_LOG_FILE_NAME=test-details.log
        CC=clang LDFLAGS='-lm' CFLAGS='-Wno-unknown-warning-option -Wswitch-default -Wno-parentheses-equality -Wno-language-extension-token -Wno-extended-offsetof -Wconditional-uninitialized -Wincompatible-pointer-types-discards-qualifiers -Wmissing-variable-declarations -Wconversion -Werror' ./configure
        make
        make check
        cat test/test-details.log

