name: GitHub CI

on: [pull_request, push]

jobs:
  gcc_simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt install check
        export CK_LOG_FILE_NAME=test-details.log
        ./configure
        make
        make check
        cat test/test-details.log

  clang_simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt install check
        export CK_LOG_FILE_NAME=test-details.log
        CC=clang ./configure
        make
        make check
        cat test/test-details.log

  # -Werror is not working with automake
  gcc_strict:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt install check
        export CK_LOG_FILE_NAME=test-details.log
        echo 'AM_CFLAGS = -Werror' >> src/Makefile.am
        CFLAGS='-DDEBUG_UNUSED -DPEDANTIC -pedantic -Wno-long-long -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wswitch -Wsign-compare -Wshadow -Wformat -Wtype-limits -Wundef -Wmissing-prototypes -Wstrict-prototypes -Wconversion' ./configure
        make
        make check
        cat test/test-details.log

  clang_strict:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt install check
        export CK_LOG_FILE_NAME=test-details.log
        CC=clang LDFLAGS='-lm' CFLAGS='-Wno-unknown-warning-option -Wswitch-default -Wno-parentheses-equality -Wno-language-extension-token -Wno-extended-offsetof -Wconditional-uninitialized -Wincompatible-pointer-types-discards-qualifiers -Wmissing-variable-declarations -Wconversion -Werror' ./configure
        make
        make check
        cat test/test-details.log

  openwrt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        wget https://downloads.openwrt.org/releases/19.07.7/targets/ath79/generic/openwrt-sdk-19.07.7-ath79-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        tar -xJf openwrt-sdk-19.07.7-ath79-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        mv openwrt-sdk-19.07.7-ath79-generic_gcc-7.5.0_musl.Linux-x86_64 openwrt-sdk
        cd openwrt-sdk
        mkdir -p package/utils/tempersensor/
        cp -R ../OpenWRT/package/ .
        cp -R ../src/ package/utils/tempersensor/
        ./scripts/feeds update -a
        ./scripts/feeds install -d m libusb-1.0
        make defconfig
        make prereq
        sed -i 's:CONFIG_SIGNED_PACKAGES=y:# CONFIG_SIGNED_PACKAGES is not set:g' .config
        make

